package com.Board;

public enum RoadTypes {
    EMPTY,
    ROAD_VERTICAL,
    ROAD_HORIZONTAL,
    ROAD_FULL_JUNCTION,
    ROAD_LEFT_TOP,
    ROAD_LEFT_BOTTOM,
    ROAD_RIGHT_TOP,
    ROAD_RIGHT_BOTTOM,
    ROAD_LEFT_TOP_RIGHT,
    ROAD_LEFT_BOTTOM_RIGHT,
    ROAD_TOP_LEFT_BOTTOM,
    ROAD_TOP_RIGHT_BOTTOM
}
